"""initial phase1 schema

Revision ID: 239714d451b1
Revises: 
Create Date: 2026-09-24 12:16:41.509364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '239714d451b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancer_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_zh', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancer_types')),
    sa.UniqueConstraint('code', name=op.f('uq_cancer_types_code'))
    )
    op.create_table('chemo_regimens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cycle_length_days', sa.SmallInteger(), nullable=True),
    sa.Column('default_total_cycles', sa.SmallInteger(), nullable=True),
    sa.Column('emetogenic_risk', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chemo_regimens')),
    sa.UniqueConstraint('name', name=op.f('uq_chemo_regimens_name'))
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generic_name', sa.String(length=100), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('drug_class', sa.String(length=50), nullable=True),
    sa.Column('default_route', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drugs')),
    sa.UniqueConstraint('generic_name', name=op.f('uq_drugs_generic_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('symptom_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_zh', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_symptom_categories_code'))
    )
    op.create_table('regimen_drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regimen_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('dose_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dose_unit', sa.String(length=20), nullable=True),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('day_of_cycle', sa.String(length=20), nullable=True),
    sa.Column('sequence', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name=op.f('fk_regimen_drugs_drug_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regimen_id'], ['chemo_regimens.id'], name=op.f('fk_regimen_drugs_regimen_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regimen_drugs')),
    sa.UniqueConstraint('regimen_id', 'drug_id', 'day_of_cycle', name=op.f('uq_regimen_drugs_regimen_id_drug_id_day_of_cycle'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.CHAR(length=36), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('public_id', name=op.f('uq_users_public_id'))
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.CHAR(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='processing', nullable=False),
    sa.Column('response_status', sa.SmallInteger(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_records_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name=op.f('uq_idempotency_records_user_id_idempotency_key'))
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_records_expires_at', ['expires_at'], unique=False)

    op.create_table('nurse_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_code', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nurse_profiles_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nurse_profiles')),
    sa.UniqueConstraint('staff_code', name=op.f('uq_nurse_profiles_staff_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_nurse_profiles_user_id'))
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.CHAR(length=36), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('baseline_ecog', sa.SmallInteger(), nullable=True),
    sa.Column('timezone', sa.String(length=40), server_default='Asia/Taipei', nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('baseline_ecog BETWEEN 0 AND 5', name=op.f('ck_patient_profiles_baseline_ecog_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_patient_profiles_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patient_profiles_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_profiles')),
    sa.UniqueConstraint('patient_code', name=op.f('uq_patient_profiles_patient_code')),
    sa.UniqueConstraint('public_id', name=op.f('uq_patient_profiles_public_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patient_profiles_user_id'))
    )
    op.create_table('symptom_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name_zh', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.String(length=255), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('step', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('min_label', sa.String(length=50), nullable=True),
    sa.Column('max_label', sa.String(length=50), nullable=True),
    sa.Column('higher_is_worse', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('ctcae_term', sa.String(length=100), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.false(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['symptom_categories.id'], name=op.f('fk_symptom_definitions_category_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_symptom_definitions_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['symptom_definitions.id'], name=op.f('fk_symptom_definitions_supersedes_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_symptom_definitions_code'))
    )
    op.create_table('symptom_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intended_for', sa.String(length=20), nullable=False),
    sa.Column('recall_period_hours', sa.SmallInteger(), nullable=True),
    sa.Column('availability', sa.String(length=20), server_default='always', nullable=False),
    sa.Column('version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_symptom_forms_created_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom_forms')),
    sa.UniqueConstraint('code', name=op.f('uq_symptom_forms_code'))
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('vital_field', sa.String(length=50), nullable=True),
    sa.Column('symptom_definition_id', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=5), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('extra_conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cancer_type_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message_template', sa.String(length=500), nullable=True),
    sa.Column('notify_patient', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('notify_nurse', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancer_type_id'], ['cancer_types.id'], name=op.f('fk_alert_rules_cancer_type_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symptom_definition_id'], ['symptom_definitions.id'], name=op.f('fk_alert_rules_symptom_definition_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules')),
    sa.UniqueConstraint('code', name=op.f('uq_alert_rules_code'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('actor_identifier', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.CHAR(length=36), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('prev_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('row_hash', sa.CHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_audit_logs_patient_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_occurred_at', ['action', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_user_id_occurred_at', ['actor_user_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_logs_patient_id_occurred_at', ['patient_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_logs_resource_type_resource_id', ['resource_type', 'resource_id'], unique=False)

    op.create_table('cancer_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('cancer_type_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=True),
    sa.Column('tnm_t', sa.String(length=10), nullable=True),
    sa.Column('tnm_n', sa.String(length=10), nullable=True),
    sa.Column('tnm_m', sa.String(length=10), nullable=True),
    sa.Column('histology', sa.String(length=100), nullable=True),
    sa.Column('biomarkers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cancer_type_id'], ['cancer_types.id'], name=op.f('fk_cancer_diagnoses_cancer_type_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cancer_diagnoses_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_cancer_diagnoses_patient_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancer_diagnoses'))
    )
    op.create_table('nurse_patient_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.false(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_nurse_patient_assignments_assigned_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], name=op.f('fk_nurse_patient_assignments_nurse_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_nurse_patient_assignments_patient_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nurse_patient_assignments')),
    sa.UniqueConstraint('nurse_id', 'patient_id', 'assigned_at', name=op.f('uq_nurse_patient_assignments_nurse_id_patient_id_assigned_at'))
    )
    with op.batch_alter_table('nurse_patient_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_nurse_patient_assignments_nurse_id_ended_at', ['nurse_id', 'ended_at'], unique=False)
        batch_op.create_index('ix_nurse_patient_assignments_patient_id_ended_at', ['patient_id', 'ended_at'], unique=False)

    op.create_table('patient_care_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('body_site', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_patient_care_alerts_patient_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_patient_care_alerts_recorded_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_care_alerts'))
    )
    with op.batch_alter_table('patient_care_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_patient_care_alerts_patient_id_is_active', ['patient_id', 'is_active'], unique=False)

    op.create_table('symptom_definition_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('value_code', sa.String(length=50), nullable=False),
    sa.Column('label_zh', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('display_order', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['symptom_definitions.id'], name=op.f('fk_symptom_definition_options_definition_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom_definition_options')),
    sa.UniqueConstraint('definition_id', 'value_code', name=op.f('uq_symptom_definition_options_definition_id_value_code'))
    )
    op.create_table('symptom_form_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.false(), nullable=True),
    sa.Column('display_condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['symptom_definitions.id'], name=op.f('fk_symptom_form_items_definition_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['form_id'], ['symptom_forms.id'], name=op.f('fk_symptom_form_items_form_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom_form_items')),
    sa.UniqueConstraint('form_id', 'definition_id', name=op.f('uq_symptom_form_items_form_id_definition_id'))
    )
    op.create_table('chemotherapy_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('regimen_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.String(length=20), nullable=True),
    sa.Column('line_of_therapy', sa.SmallInteger(), nullable=True),
    sa.Column('total_cycles', sa.SmallInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discontinue_reason', sa.Text(), nullable=True),
    sa.Column('attending_physician_name', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_chemotherapy_plans_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['cancer_diagnoses.id'], name=op.f('fk_chemotherapy_plans_diagnosis_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_chemotherapy_plans_patient_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regimen_id'], ['chemo_regimens.id'], name=op.f('fk_chemotherapy_plans_regimen_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chemotherapy_plans'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('alert_rule_id', sa.Integer(), nullable=True),
    sa.Column('event_key', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.false(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_notifications_acknowledged_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name=op.f('fk_notifications_alert_rule_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_notifications_patient_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_event_key', ['event_key'], unique=False)
        batch_op.create_index('ix_notifications_patient_id_alert_rule_id_created_at', ['patient_id', 'alert_rule_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_recipient_id_is_read_created_at', ['recipient_id', 'is_read', 'created_at'], unique=False)

    op.create_table('chemotherapy_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('bsa_m2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('dose_modification_pct', sa.SmallInteger(), server_default='100', nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delay_days', sa.SmallInteger(), nullable=True),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('nadir_start_day', sa.SmallInteger(), nullable=True),
    sa.Column('nadir_end_day', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_chemotherapy_cycles_patient_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['chemotherapy_plans.id'], name=op.f('fk_chemotherapy_cycles_plan_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chemotherapy_cycles')),
    sa.UniqueConstraint('plan_id', 'cycle_number', name=op.f('uq_chemotherapy_cycles_plan_id_cycle_number'))
    )
    with op.batch_alter_table('chemotherapy_cycles', schema=None) as batch_op:
        batch_op.create_index('ix_chemotherapy_cycles_patient_id_scheduled_date', ['patient_id', 'scheduled_date'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('appointment_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_min', sa.SmallInteger(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('rescheduled_from_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_appointments_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['chemotherapy_cycles.id'], name=op.f('fk_appointments_cycle_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_appointments_patient_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], name=op.f('fk_appointments_rescheduled_from_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_patient_id_scheduled_at', ['patient_id', 'scheduled_at'], unique=False)
        batch_op.create_index('ix_appointments_scheduled_at_status', ['scheduled_at', 'status'], unique=False)

    op.create_table('medication_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('medication_type', sa.String(length=20), nullable=False),
    sa.Column('dose_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dose_unit', sa.String(length=20), nullable=False),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('administered_at', sa.DateTime(), nullable=False),
    sa.Column('infusion_duration_min', sa.Integer(), nullable=True),
    sa.Column('administration_status', sa.String(length=20), nullable=False),
    sa.Column('reaction_notes', sa.Text(), nullable=True),
    sa.Column('administered_by', sa.Integer(), nullable=True),
    sa.Column('cycle_day', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('record_status', sa.String(length=20), server_default='final', nullable=False),
    sa.Column('amends_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], name=op.f('fk_medication_records_administered_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['amends_id'], ['medication_records.id'], name=op.f('fk_medication_records_amends_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['chemotherapy_cycles.id'], name=op.f('fk_medication_records_cycle_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name=op.f('fk_medication_records_drug_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_medication_records_patient_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_records'))
    )
    with op.batch_alter_table('medication_records', schema=None) as batch_op:
        batch_op.create_index('ix_medication_records_cycle_id', ['cycle_id'], unique=False)
        batch_op.create_index('ix_medication_records_patient_id_administered_at', ['patient_id', 'administered_at'], unique=False)

    op.create_table('appointment_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('instruction_type', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('is_highlighted', sa.Boolean(), server_default=sa.true(), nullable=True),
    sa.Column('display_order', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_instructions_appointment_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_instructions'))
    )
    op.create_table('nursing_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('assessed_by', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('ecog_status', sa.SmallInteger(), nullable=True),
    sa.Column('overall_condition', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('chemo_readiness', sa.String(length=20), nullable=True),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('sign_status', sa.String(length=10), server_default='draft', nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('cycle_day', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('record_status', sa.String(length=20), server_default='final', nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('amends_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ecog_status BETWEEN 0 AND 5', name=op.f('ck_nursing_assessments_ecog_status_range')),
    sa.ForeignKeyConstraint(['amends_id'], ['nursing_assessments.id'], name=op.f('fk_nursing_assessments_amends_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_nursing_assessments_appointment_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], name=op.f('fk_nursing_assessments_assessed_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['chemotherapy_cycles.id'], name=op.f('fk_nursing_assessments_cycle_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_nursing_assessments_patient_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nursing_assessments'))
    )
    with op.batch_alter_table('nursing_assessments', schema=None) as batch_op:
        batch_op.create_index('ix_nursing_assessments_assessed_by_assessed_at', ['assessed_by', 'assessed_at'], unique=False)
        batch_op.create_index('ix_nursing_assessments_patient_id_assessed_at', ['patient_id', 'assessed_at'], unique=False)
        batch_op.create_index('ix_nursing_assessments_sign_status', ['sign_status'], unique=False)

    op.create_table('nursing_assessment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('item_status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('display_order', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['nursing_assessments.id'], name=op.f('fk_nursing_assessment_items_assessment_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nursing_assessment_items'))
    )
    op.create_table('symptom_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('form_version', sa.SmallInteger(), nullable=True),
    sa.Column('nursing_assessment_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=20), server_default='submitted', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('cycle_day', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('record_status', sa.String(length=20), server_default='final', nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('amends_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['amends_id'], ['symptom_records.id'], name=op.f('fk_symptom_records_amends_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['chemotherapy_cycles.id'], name=op.f('fk_symptom_records_cycle_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['symptom_forms.id'], name=op.f('fk_symptom_records_form_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nursing_assessment_id'], ['nursing_assessments.id'], name=op.f('fk_symptom_records_nursing_assessment_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_symptom_records_patient_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_symptom_records_reported_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_symptom_records_reviewed_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom_records'))
    )
    with op.batch_alter_table('symptom_records', schema=None) as batch_op:
        batch_op.create_index('ix_symptom_records_patient_id_recorded_at', ['patient_id', 'recorded_at'], unique=False)
        batch_op.create_index('ix_symptom_records_review_status_recorded_at', ['review_status', 'recorded_at'], unique=False)

    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('nursing_assessment_id', sa.Integer(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temperature_site', sa.String(length=10), nullable=True),
    sa.Column('heart_rate_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('systolic_bp_mmhg', sa.SmallInteger(), nullable=True),
    sa.Column('diastolic_bp_mmhg', sa.SmallInteger(), nullable=True),
    sa.Column('bp_measure_site', sa.String(length=20), nullable=True),
    sa.Column('respiratory_rate', sa.SmallInteger(), nullable=True),
    sa.Column('spo2_pct', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pain_score', sa.SmallInteger(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cycle_day', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('record_status', sa.String(length=20), server_default='final', nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('amends_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('pain_score BETWEEN 0 AND 10', name=op.f('ck_vital_signs_pain_score_range')),
    sa.ForeignKeyConstraint(['amends_id'], ['vital_signs.id'], name=op.f('fk_vital_signs_amends_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['chemotherapy_cycles.id'], name=op.f('fk_vital_signs_cycle_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nursing_assessment_id'], ['nursing_assessments.id'], name=op.f('fk_vital_signs_nursing_assessment_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_vital_signs_patient_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_vital_signs_recorded_by'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vital_signs'))
    )
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.create_index('ix_vital_signs_patient_id_measured_at', ['patient_id', 'measured_at'], unique=False)

    op.create_table('symptom_record_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom_record_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ctcae_grade', sa.SmallInteger(), nullable=True),
    sa.Column('body_location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ctcae_grade BETWEEN 0 AND 5', name=op.f('ck_symptom_record_values_ctcae_grade_range')),
    sa.ForeignKeyConstraint(['definition_id'], ['symptom_definitions.id'], name=op.f('fk_symptom_record_values_definition_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['option_id'], ['symptom_definition_options.id'], name=op.f('fk_symptom_record_values_option_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['symptom_record_id'], ['symptom_records.id'], name=op.f('fk_symptom_record_values_symptom_record_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom_record_values')),
    sa.UniqueConstraint('symptom_record_id', 'definition_id', name=op.f('uq_symptom_record_values_symptom_record_id_definition_id'))
    )
    with op.batch_alter_table('symptom_record_values', schema=None) as batch_op:
        batch_op.create_index('ix_symptom_record_values_definition_id_symptom_record_id', ['definition_id', 'symptom_record_id'], unique=False)

    op.create_table('symptom_record_value_options',
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['symptom_definition_options.id'], name=op.f('fk_symptom_record_value_options_option_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['value_id'], ['symptom_record_values.id'], name=op.f('fk_symptom_record_value_options_value_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('value_id', 'option_id', name=op.f('pk_symptom_record_value_options'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom_record_value_options')
    with op.batch_alter_table('symptom_record_values', schema=None) as batch_op:
        batch_op.drop_index('ix_symptom_record_values_definition_id_symptom_record_id')

    op.drop_table('symptom_record_values')
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_index('ix_vital_signs_patient_id_measured_at')

    op.drop_table('vital_signs')
    with op.batch_alter_table('symptom_records', schema=None) as batch_op:
        batch_op.drop_index('ix_symptom_records_review_status_recorded_at')
        batch_op.drop_index('ix_symptom_records_patient_id_recorded_at')

    op.drop_table('symptom_records')
    op.drop_table('nursing_assessment_items')
    with op.batch_alter_table('nursing_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_nursing_assessments_sign_status')
        batch_op.drop_index('ix_nursing_assessments_patient_id_assessed_at')
        batch_op.drop_index('ix_nursing_assessments_assessed_by_assessed_at')

    op.drop_table('nursing_assessments')
    op.drop_table('appointment_instructions')
    with op.batch_alter_table('medication_records', schema=None) as batch_op:
        batch_op.drop_index('ix_medication_records_patient_id_administered_at')
        batch_op.drop_index('ix_medication_records_cycle_id')

    op.drop_table('medication_records')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_scheduled_at_status')
        batch_op.drop_index('ix_appointments_patient_id_scheduled_at')

    op.drop_table('appointments')
    with op.batch_alter_table('chemotherapy_cycles', schema=None) as batch_op:
        batch_op.drop_index('ix_chemotherapy_cycles_patient_id_scheduled_date')

    op.drop_table('chemotherapy_cycles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_recipient_id_is_read_created_at')
        batch_op.drop_index('ix_notifications_patient_id_alert_rule_id_created_at')
        batch_op.drop_index('ix_notifications_event_key')

    op.drop_table('notifications')
    op.drop_table('chemotherapy_plans')
    op.drop_table('symptom_form_items')
    op.drop_table('symptom_definition_options')
    with op.batch_alter_table('patient_care_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_care_alerts_patient_id_is_active')

    op.drop_table('patient_care_alerts')
    with op.batch_alter_table('nurse_patient_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_nurse_patient_assignments_patient_id_ended_at')
        batch_op.drop_index('ix_nurse_patient_assignments_nurse_id_ended_at')

    op.drop_table('nurse_patient_assignments')
    op.drop_table('cancer_diagnoses')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_resource_type_resource_id')
        batch_op.drop_index('ix_audit_logs_patient_id_occurred_at')
        batch_op.drop_index('ix_audit_logs_actor_user_id_occurred_at')
        batch_op.drop_index('ix_audit_logs_action_occurred_at')

    op.drop_table('audit_logs')
    op.drop_table('alert_rules')
    op.drop_table('symptom_forms')
    op.drop_table('symptom_definitions')
    op.drop_table('patient_profiles')
    op.drop_table('nurse_profiles')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_records_expires_at')

    op.drop_table('idempotency_records')
    op.drop_table('auth_tokens')
    op.drop_table('users')
    op.drop_table('regimen_drugs')
    op.drop_table('symptom_categories')
    op.drop_table('roles')
    op.drop_table('drugs')
    op.drop_table('chemo_regimens')
    op.drop_table('cancer_types')
    # ### end Alembic commands ###
