"""notification delivery email mode

Email content policy for nurse-sent notifications: three nullable columns on
``notification_deliveries`` — ``content_category`` (the nurse's topic), ``email_mode_requested`` and
``email_mode`` (applied; ``full`` → ``summary`` for sensitive topics). ``notifications`` is not changed.
Existing rows keep NULL (= the earlier summary email). Downgrade drops the three columns only.

Revision ID: 470df9cf2163
Revises: 8c6b981c2152
Create Date: 2026-10-06 11:21:45.065810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470df9cf2163'
down_revision = '8c6b981c2152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email_mode_requested', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('email_mode', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_column('email_mode')
        batch_op.drop_column('email_mode_requested')
        batch_op.drop_column('content_category')

    # ### end Alembic commands ###
