"""patient contacts and notification deliveries

Patient profile + email notification sprint. Adds two tables, changes no existing table:

- ``patient_contacts`` (1:1 patient_profiles, RESTRICT): the patient's own contact email (not the
  login ``users.email``), ``email_verified_at`` and ``email_notification_enabled`` (default false).
  The Phase 2 columns of this table (phone, address, ...) are not created yet.
- ``notification_deliveries`` (N:1 notifications, CASCADE): email delivery of a notification with
  its own status (pending / sent / failed / skipped), separate from ``notifications.status``.

Downgrade drops both tables: patient contact emails and delivery records are lost; every other
table (and the notifications themselves) is untouched.

Revision ID: 8c6b981c2152
Revises: ea84e6940c21
Create Date: 2026-10-02 16:38:35.926692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6b981c2152'
down_revision = 'ea84e6940c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email_notification_enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_patient_contacts_patient_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_contacts')),
    sa.UniqueConstraint('patient_id', name=op.f('uq_patient_contacts_patient_id'))
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('skip_reason', sa.String(length=30), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('recipient_masked', sa.String(length=255), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_deliveries_notification_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_notification_deliveries_notification_id', ['notification_id'], unique=False)
        batch_op.create_index('ix_notification_deliveries_status_created_at', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_deliveries_status_created_at')
        batch_op.drop_index('ix_notification_deliveries_notification_id')

    op.drop_table('notification_deliveries')
    op.drop_table('patient_contacts')
    # ### end Alembic commands ###
