"""notification lifecycle and recommended action

Adds the clinical handling lifecycle to notifications (new → acknowledged → in_progress →
resolved) and alert_rules.recommended_action. Existing columns are unchanged.

Backfill: before this revision a set ``acknowledged_at`` meant the alert was resolved, so
those rows become ``resolved`` with resolved_* / started_* copied from acknowledged_*;
every other row becomes ``new``. Downgrade restores the old meaning (only resolved rows
keep acknowledged_*).

Revision ID: ea84e6940c21
Revises: 9253ef8ff76f
Create Date: 2026-09-24 18:48:25.184881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea84e6940c21'
down_revision = '9253ef8ff76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_action', sa.String(length=500), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='new', nullable=False))
        batch_op.add_column(sa.Column('started_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_notifications_patient_id_status_created_at', ['patient_id', 'status', 'created_at'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_notifications_resolved_by'), 'users', ['resolved_by'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_started_by'), 'users', ['started_by'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
    op.execute(
        "UPDATE notifications SET status = 'resolved', "
        "resolved_by = acknowledged_by, resolved_at = acknowledged_at, "
        "started_by = acknowledged_by, started_at = acknowledged_at "
        "WHERE acknowledged_at IS NOT NULL"
    )


def downgrade():
    # Old schema: acknowledged_at set == resolved. Alerts taken over but not yet resolved go back to open.
    op.execute(
        "UPDATE notifications SET acknowledged_by = NULL, acknowledged_at = NULL "
        "WHERE status <> 'resolved'"
    )
    op.execute(
        "UPDATE notifications SET acknowledged_by = resolved_by, acknowledged_at = resolved_at "
        "WHERE status = 'resolved'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_started_by'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_resolved_by'), type_='foreignkey')
        batch_op.drop_index('ix_notifications_patient_id_status_created_at')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('started_at')
        batch_op.drop_column('started_by')
        batch_op.drop_column('status')

    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_column('recommended_action')

    # ### end Alembic commands ###
